version: 2

jobs:
  test_oj:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/kmyk/online-judge-tools
            cd online-judge-tools
            pip3 install -e .
            cd ../test
            ./test.sh
