version: 2

jobs:
  build:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/kmyk/online-judge-tools
            cd online-judge-tools
            pip3 install --user -e .
            cd ../test_oj
            ./test.sh
